### PR TITLE
Appveyor deployment script and badge

### PR DESCRIPTION
**Pull request by arl**
Doing early :smile: PR so that we can see if  some differences will arise due to forked / fork repo mismatch. 

Probably need to replace the GitHub encrypted `auth_token` in my script by develers one
@rasky can you provide that?

### CODE REVIEW

**Comment by rasky** [comment]
@aurelien-rainone try: `secure: DP+lbxV/P0SXFccQVIJe0u9Nni6jRs9xxx4JW6Mp9z4DWZIoYZSYnGCCDw2q37Et`

**Comment by rasky** [comment]
also don't forget to revoke yours afterwards

**Comment by arl** [comment]
- done replacing auth_token,

Now there's also the appveyor badge in README.md  [Build status](https://ci.appveyor.com/project/aurelien-rainone/cutecom-ng) that needs to be updated to reflect **develer** repo status and not mine, but there's a hash in the url that i don't think i have access to, @rasky can you provide it or directly modify the README.md please?

**Comment by arl** [comment]
@lmancini @gvaldambrini here's appveyor workflow :

### PR Request on develersrl/cutecom-ng

trigger build on Appveyor. Build status is seen in the PR page and create an Appveyor artifact (a zip) that is **not** pushed to [develersrl/cutecom-ng/releases](https://github.com/develersrl/cutecom-ng/releases) but downloadable in the artifacts tab of [Appveyor web gui](https://ci.appveyor.com/project/develer/cutecom-ng)

### Push to master

(either a direct push to master or a PR merge) triggers a build, and pushes  `cutecom-ng.win-latest.zip` to [develersrl/cutecom-ng/releases](https://github.com/develersrl/cutecom-ng/releases), this zip is showed as a pre-release and is public (visible and downloadable for everybody)

### Git Tags

same as **pushes to master** above but release is named after `cutecom-ng.win-TAG.zip` and pushed to [develersrl/cutecom-ng/releases](https://github.com/develersrl/cutecom-ng/releases) as a _draft_ that requires a manual confirmation from one of repo's owner before becoming public

**Pull request merged**
